name: chessclock
description: Reloj de ajedrez para dos participantes, completamente sin conexión.
publish_to: none
version: 1.1.0+2
environment:
  sdk: '>=3.11.5 <4.0.0'
  flutter: '>=3.41.9'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
